
application: lovebrary
version: 0-1-alpha
runtime: python
api_version: 1

handlers:
- url: /
  script: home.py

- url: /index
  script: home.py

- url: /stylesheets
  static_dir: stylesheets

- url: /favicon.ico
  static_files: static/site/favicon.ico
  upload: static/site/favicon.ico

- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)

- url: /admin/.*
  script: admin.py
  login: admin
  secure: optional

- url: /.*
  script: not_found.py
